site_name: Onbon Docs



nav:
    - 主页: index.md
    - 单双色系列:
        - 开发指南: zh/dual/dual.md
        - JAVA: zh/dual/java.md
        - C/C++: zh/dual/c.md
    - 字库系列:
        - 开发指南: zh/k/k.md
        - JAVA: zh/k/java.md
    - 常用工具:
        - 网络抓包: zh/tool/wireshark.md
    - 关于我们 : 'zh/about.md'
    

theme: 
    name: readthedocs
    highlightjs: true
    navigation_depth: 4

# repository addr
repo_url: https://github.com/onbonlab/onbonlab.github.io.git

repo_name: 'GitHub'

site_author: 'tataba'

# 图标
site_favicon: favicon.ico

site_description: "This is the doc of onbon dev."

# 版权
copyright: "Copyright © 2020 onbon. All rights reserved. "



markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - "https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js"
  - 'js/my.js'
  
extra_css:
  - 'css/my.css'
  - "https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css"
  
extra:
  search:
    language: 'jp'

